[package]
name = "chat-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dotenv = "0.15.0"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
mongodb = "3.1.0"
serde = "1.0.210"
thiserror = "1.0.63"
tokio = "1.40.0"
tokio-tungstenite = "0.24.0"
